"""add sections table and section_id fk to students and schedules

Revision ID: 97883093d6eb
Revises: 6a7153924ab3
Create Date: 2026-03-17 06:58:06.652145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97883093d6eb'
down_revision = '6a7153924ab3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program', sa.String(length=20), nullable=False),
    sa.Column('year_level', sa.Integer(), nullable=False),
    sa.Column('section_letter', sa.String(length=5), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('program', 'year_level', 'section_letter', name='uq_section_combo')
    )
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('section_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_schedules_section_id'), ['section_id'], unique=False)
        batch_op.create_foreign_key(None, 'sections', ['section_id'], ['id'])

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('section_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_students_section_id'), ['section_id'], unique=False)
        batch_op.create_foreign_key(None, 'sections', ['section_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_students_section_id'))
        batch_op.drop_column('section_id')

    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_schedules_section_id'))
        batch_op.drop_column('section_id')

    op.drop_table('sections')
    # ### end Alembic commands ###
