"""add gender column to students

Revision ID: b386fe06d6b1
Revises: f3a9b2d4c6e1
Create Date: 2026-03-16 06:19:27.995251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b386fe06d6b1'
down_revision = 'f3a9b2d4c6e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('gender')

    # ### end Alembic commands ###
