"""add_grade_audit_remarks_grade_rel

Revision ID: c685a10fea77
Revises: 92127d8a5a8a
Create Date: 2026-03-09 00:08:23.411730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c685a10fea77'
down_revision = '92127d8a5a8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grade_audits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('old_remarks', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('new_remarks', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grade_audits', schema=None) as batch_op:
        batch_op.drop_column('new_remarks')
        batch_op.drop_column('old_remarks')

    # ### end Alembic commands ###
